# Polynomial Linear Regression

## y = b0 + b1x1 + b2x2^2 + ...

### Why Linear:

#### Linear refers to coefficients.

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [50]:
data = pd.read_csv('Position_Salaries.csv')

X = data.iloc[: , 1:2].values
y = data.iloc[:, -1].values

In [ ]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0, random_state=42)
#We won't use train-test split in this example as our sample size is relatively small (n=10)

In [ ]:
# Fitting Linear Regression to the dataset

from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

In [ ]:
# Fitting Polynomial Regression to the dataset

from sklearn.preprocessing import PolynomialFeatures
pol_reg = PolynomialFeatures(degree = 5)
X_poly = pol_reg.fit_transform(X_train)

#Now we need to create a new Linear regressor object to fit our polynomial 
lin_reg2 = LinearRegression()
lin_reg2.fit(X_poly, y_train)


In [ ]:
'''Parameters
----------
degree : integer
    The degree of the polynomial features. Default = 2.

interaction_only : boolean, default = False
    If true, only interaction features are produced: features that are
    products of at most ``degree`` *distinct* input features (so not
    ``x[1] ** 2``, ``x[0] * x[2] ** 3``, etc.).

include_bias : boolean
    If True (default), then include a bias column, the feature in which
    all polynomial powers are zero (i.e. a column of ones - acts as an
    intercept term in a linear model).

Examples
--------
>>> X = np.arange(6).reshape(3, 2)
>>> X
array([[0, 1],
       [2, 3],
       [4, 5]])
>>> poly = PolynomialFeatures(2)
>>> poly.fit_transform(X)
array([[  1.,   0.,   1.,   0.,   0.,   1.],
       [  1.,   2.,   3.,   4.,   6.,   9.],
       [  1.,   4.,   5.,  16.,  20.,  25.]])
>>> poly = PolynomialFeatures(interaction_only=True)
>>> poly.fit_transform(X)
array([[  1.,   0.,   1.,   0.],
       [  1.,   2.,   3.,   6.],
       [  1.,   4.,   5.,  20.]])'''

In [ ]:
#Visualizing the Linear Regression Results
plt.figure(figsize = [15,8])
plt.scatter(X , y , color ='red')
plt.plot(X_train, lin_reg.predict(X_train), color='blue')
plt.title('Linear Regression Model')
plt.xlabel('Job Title')
plt.ylabel('Salary')
plt.grid('on')

In [ ]:
#Visualizing the Polynomial Regression Results

#Creating a smoother line
X_grid = np.arange(min(X),max(X),.1)
X_grid = X_grid.reshape((len(X_grid),1))


plt.figure(figsize = [15,8])
plt.scatter(X , y , color ='red')
plt.plot(sorted(X_grid), sorted(lin_reg2.predict(pol_reg.fit_transform(X_grid)),reverse=False), color='blue')
plt.title('Polynomial Regression Model')
plt.xlabel('Job Title')
plt.ylabel('Salary')
plt.grid('on')

In [ ]:
# Predicting a new result with Linear Regression
lin_reg.predict(6.5)

In [ ]:
# Predicting a new result with Polynomia Regression
lin_reg2.predict(pol_reg.fit_transform(6.5))